name: Daniel's site
markdown: kramdown
prose:
  rooturl: '_posts'
  siteurl: 'http://danielscw.github.io'
  media: 'media'
  ignore:
    - README.md
    - index.md
    - _config.yml
    - /_layouts
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "Level1Group"
        field:
          element: "text"
          label: "Level 1 group"
          value: "default"
      - name: "Level2Group"
        field:
          element: "text"
          label: "Level 2 group"
          value: "default"
